version: "3.4"

services:
    alpine_hugo:
        build: .
        volumes:
            - ".:/src"
        ports:
            - "1313:1313"
        command: hugo server -D --buildDrafts --watch --bind 0.0.0.0

networks:
    default:
        external:
            name: gleyze